[package]
name = "rust-code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hello"
path = "src/hello/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
